server:
  applicationConnectors:
    - type: http
      port: 11016
      bindHost: 0.0.0.0 # only bind to loopback
      headerCacheSize: 512 bytes
      outputBufferSize: 32KiB
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      inputBufferSize: 8KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
      soLingerTime: 345s
      useServerHeader: false
      useDateHeader: true
      useForwardedHeaders: true

assets:
  overrides:
    /assets: client/dist/
  cacheSpec: maximumSize=0
  
logging:
  level: "INFO"
  loggers:
    "com.greylogix": INFO
    #"org.eclipse.jetty": OFF
    "org.eclipse.jetty": WARN
    "io.dropwizard.jersey": INFO
    "org.apache.http": OFF
    "org.apache.commons.beanutils": OFF
    "org.atmosphere.cpr": DEBUG
    "org.hibernate.validator.internal": OFF
    "org.atmosphere.container.Jetty9AsyncSupportWithWebSocket": OFF
    "com.greylogix.smartgyportal.socket.threads": DEBUG
    "org.apache.shiro.web.servlet.AbstractShiroFilter": WARN
    "org.mongodb.morphia.mapping.MappedClass": WARN
    "org.atmosphere.cpr.DefaultBroadcaster": WARN
    "org.apache.shiro": WARN
    "com.codahale.metrics": WARN
    "net.jodah.lyra.internal": WARN
    "net.sf.ehcache": INFO
    
  appenders: 
    - type: console

    # Do not display log statements below this threshold to stdout.
      threshold: ALL


  # ...
  # Settings for logging to a file.
    - type: file
      threshold: ALL

      # Using this logfile path for developing
      currentLogFilename: ./logs/operating-Numbers.log
      archivedLogFilenamePattern: ./logs/operating-Numbers-%d.log.gz

      # Using this logfile path for production
      #currentLogFilename: /var/log/opnum/opnum.log
      #archivedLogFilenamePattern: /var/log/opnum/opnum-%d.log.gz

      archive: true
      archivedFileCount: 5
      timeZone: UTC



